language: node_js
branches:
  only:
    - master
before_install:
  - npm --version
install:
  - npm i
before_script:
  - export store_api_jwt_private_key=your_private_key
  - export store_api_bcrypt_salt=5
  - node sequelize.js
  - node seed_db.js
  - npm run sequelize-test
script:
  - npm test
